name: Commit Message Lint

on:
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Commitlint
      run: |
        npm install
        npx commitlint --from=HEAD~1 --to=HEAD
      env:
        CI: true
